<h2 class="yadg-h2 centered">AngouriMath.Core.Exceptions</h2><hr/><p class="yadg-p "><a href="namespaces.html">&#8592; Back to list of namespaces</a></p><p class="yadg-p ">Classes within the AngouriMath.Core.Exceptions namespace</p><p class="yadg-p "><ul class="yadg-ul "><li class="yadg-li yadg-class yadg-list"><h3 class="yadg-h3 ">AngouriBugException</h3><p class="yadg-p "><strong class="yadg-strong ">Summary</strong></p><div class='yadg-summary'>If one was thrown, the exception is probably not foreseen by AM. Report it is an issue</div></li><li class="yadg-li yadg-class yadg-list"><h3 class="yadg-h3 ">AngouriMathBaseException</h3><p class="yadg-p "><strong class="yadg-strong ">Summary</strong></p><div class='yadg-summary'            This is the base exception of all exceptions thrown by AngouriMath. <br>            If one needs to catch all exceptions from AngouriMath, it is enough<br>            to catch this one<br>            </div></li><li class="yadg-li yadg-class yadg-list"><h3 class="yadg-h3 ">CannotEvalException</h3><p class="yadg-p "><strong class="yadg-strong ">Summary</strong></p><div class='yadg-summary'>Is thrown when something cannot be collapsed into a single number or boolean</div></li><li class="yadg-li yadg-class yadg-list"><h3 class="yadg-h3 ">CannotParseInstanceException</h3><p class="yadg-p "><strong class="yadg-strong ">Summary</strong></p><div class='yadg-summary'            May be thrown when trying to parse an instance from a string<br>            Set set = "{ 1, 2 }"; // not thrown<br>            Set set = "1 + 2"; // thrown<br>            </div></li><li class="yadg-li yadg-class yadg-list"><h3 class="yadg-h3 ">ElementInSetAmbiguousException</h3><p class="yadg-p "><strong class="yadg-strong ">Summary</strong></p><div class='yadg-summary'> Cannot figure out whether the entity is in the set </div></li><li class="yadg-li yadg-class yadg-list"><h3 class="yadg-h3 ">FunctionArgumentCountException</h3><p class="yadg-p "><strong class="yadg-strong ">Summary</strong></p><div class='yadg-summary'>Thrown when a wrong number of arguments are encountered when parsing a function</div></li><li class="yadg-li yadg-class yadg-list"><h3 class="yadg-h3 ">FutureReleaseException</h3><p class="yadg-p "><strong class="yadg-strong ">Summary</strong></p><div class='yadg-summary'            Is thrown when the requested feature is still under developing<br>            or not considered to be developed at all<br>            </div></li><li class="yadg-li yadg-class yadg-list"><h3 class="yadg-h3 ">InvalidArgumentParseException</h3><p class="yadg-p "><strong class="yadg-strong ">Summary</strong></p><div class='yadg-summary'>Thrown when an invalid argument passed to a AM's function</div></li><li class="yadg-li yadg-class yadg-list"><h3 class="yadg-h3 ">InvalidMatrixOperationException</h3><p class="yadg-p "><strong class="yadg-strong ">Summary</strong></p><div class='yadg-summary'>Thrown in matrix operations</div></li><li class="yadg-li yadg-class yadg-list"><h3 class="yadg-h3 ">InvalidNumberException</h3><p class="yadg-p "><strong class="yadg-strong ">Summary</strong></p><div class='yadg-summary'>Thrown when an invalid number is passed as an argument</div></li><li class="yadg-li yadg-class yadg-list"><h3 class="yadg-h3 ">InvalidNumericSystemException</h3><p class="yadg-p "><strong class="yadg-strong ">Summary</strong></p><div class='yadg-summary'></div></li><li class="yadg-li yadg-class yadg-list"><h3 class="yadg-h3 ">InvalidProtocolProvided</h3><p class="yadg-p "><strong class="yadg-strong ">Summary</strong></p><div class='yadg-summary'            Occurs when no custom compilation protocol was provided, while the built-in one<br>            does not have the given type defined for the given operator. To resolve it,<br>            create your own <a href="AngouriMath.Core.Compilation.IntoLinq/CompilationProtocol.html">CompilationProtocol</a>.<br>            </div></li><li class="yadg-li yadg-class yadg-list"><h3 class="yadg-h3 ">LimitOperationNotSupportedException</h3><p class="yadg-p "><strong class="yadg-strong ">Summary</strong></p><div class='yadg-summary'>Thrown inside operations related to limits</div></li><li class="yadg-li yadg-class yadg-list"><h3 class="yadg-h3 ">MathSException</h3><p class="yadg-p "><strong class="yadg-strong ">Summary</strong></p><div class='yadg-summary'>If one is thrown, the user's input is invalid</div></li><li class="yadg-li yadg-class yadg-list"><h3 class="yadg-h3 ">NotSufficientlySupportedException</h3><p class="yadg-p "><strong class="yadg-strong ">Summary</strong></p><div class='yadg-summary'            In case if AM or other parts do not support something, <br>            for example, it may occur if either AM or SymPy does not<br>            support some specific feature<br>            </div></li><li class="yadg-li yadg-class yadg-list"><h3 class="yadg-h3 ">NumberCastException</h3><p class="yadg-p "><strong class="yadg-strong ">Summary</strong></p><div class='yadg-summary'>Thrown when invalid cast encountered</div></li><li class="yadg-li yadg-class yadg-list"><h3 class="yadg-h3 ">ParseException</h3><p class="yadg-p "><strong class="yadg-strong ">Summary</strong></p><div class='yadg-summary'>Thrown when trying to parse an invalid string</div></li><li class="yadg-li yadg-class yadg-list"><h3 class="yadg-h3 ">SolveRequiresStatementException</h3><p class="yadg-p "><strong class="yadg-strong ">Summary</strong></p><div class='yadg-summary'> Thrown if instead of a statement another expression is put into Solve </div></li><li class="yadg-li yadg-class yadg-list"><h3 class="yadg-h3 ">TreeException</h3><p class="yadg-p "><strong class="yadg-strong ">Summary</strong></p><div class='yadg-summary'>Thrown when an invalid node or combination of nodes in the expression tree is encountered</div></li><li class="yadg-li yadg-class yadg-list"><h3 class="yadg-h3 ">UncompilableNodeException</h3><p class="yadg-p "><strong class="yadg-strong ">Summary</strong></p><div class='yadg-summary'>Thrown when trying to compile and a node cannot be compiled</div></li><li class="yadg-li yadg-class yadg-list"><h3 class="yadg-h3 ">UnhandledParseException</h3><p class="yadg-p "><strong class="yadg-strong ">Summary</strong></p><div class='yadg-summary'>Can only occur in the ANTLR parser when it is unclear what exactly happened</div></li><li class="yadg-li yadg-class yadg-list"><h3 class="yadg-h3 ">UnrecognizedDomainException</h3><p class="yadg-p "><strong class="yadg-strong ">Summary</strong></p><div class='yadg-summary'>Thrown when non-known domain is passed to the domain function</div></li><li class="yadg-li yadg-class yadg-list"><h3 class="yadg-h3 ">WrongNumberOfArgumentsException</h3><p class="yadg-p "><strong class="yadg-strong ">Summary</strong></p><div class='yadg-summary'>Quite general, is thrown when too many or too few of whatever is provided</div></li></ul></p>